config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :complaints
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "complaints#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:name, :email, :phone, :order_number, :zip_code, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
        <% complaint.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :order_number %>
    <%= form.number_field :order_number %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.number_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Order number</th>
      <th>Zip code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.name %></td>
        <td><%= complaint.email %></td>
        <td><%= complaint.phone %></td>
        <td><%= complaint.order_number %></td>
        <td><%= complaint.zip_code %></td>
        <td><%= complaint.description %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @complaint.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @complaint.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @complaint.phone %>
</p>

<p>
  <strong>Order number:</strong>
  <%= @complaint.order_number %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @complaint.zip_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @complaint.description %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReclameAi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <%= yield %>
  </body>
</html>